mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: 192.168.1.100
    port: 1883
    keepalive: 60
  private_path: device/001
bridge:
  # ROS to mqtt message to change modes in the warning lamp
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: enway_msgs.msg:WarnStates
    topic_from: /warning_light
    topic_to: warning_light
